rekcurd/dashboard

- app/Dockerfile
- app/apis/__init__.py
- app/app.py
- app/auth/__init__.py
- app/auth/ldap.py
- app/requirements.txt
- app/settings.yml
- frontend/src/actions/index.tsx
- frontend/src/apis/Core/index.tsx
- frontend/src/apis/index.tsx
- frontend/src/app.tsx
- frontend/src/components/App/Layout/index.tsx
- frontend/src/components/App/Login/fields.tsx
- frontend/src/components/App/Login/form.tsx
- frontend/src/components/App/Login/index.tsx
- frontend/src/components/App/index.tsx
- frontend/src/components/Common/APIRequestResultsRenderer/index.tsx
- frontend/src/components/misc/NavigationBar/index.tsx
- frontend/src/reducers/index.tsx
- frontend/tslint.json
LDAP authentication enabled by setting.
- Backend
- Added LDAP authentication API
- If the authentication setting is enabled, all API requests require `jwt` token in the header.
- Frontend
- Added login form
- If API returns `401` unauthorized response, frontend app redirects to the login form.
Feature
N/A
Activated by un-commenting the `auth` part of `settings.yml`
> Add LDAP authentication

- frontend/src/components/misc/Forms/DeploymentSettingFormFields/index.tsx
For better understandings, I have changed the frontend texts.
- Change text
Minor
N/A
N/A
> Change text

- frontend/src/index.html
Add favicon link.
- Add favicon link
Minor
N/A
N/A
> Add favicon

- app/start.sh
https://github.com/drucker/drucker-grpc-proto/pull/3
- Change code-generator
Bugfix
N/A
N/A
> [Hotfix] Change code generator

- app/apis/api_kubernetes.py
- app/apis/api_service.py
- frontend/src/components/App/SaveApplication/ApplicationDeploymentForm.tsx
- frontend/src/components/App/Service/ServiceDeployment/ServiceDeploymentForm.tsx
- frontend/src/components/App/Service/ServiceDeployment/index.tsx
- frontend/src/components/misc/Forms/DeploymentSettingFormFields/index.tsx
For this modification, you can select the existing model when you run `Add Service`.
- Add `service_model_assignment` in backend
- Add `Model assignment` in frontend
Feature
N/A
N/A
> Add a function that allows you to select a model when booting a new service

- app/apis/api_kubernetes.py
fix invalid datetime
- Fix `api_kubernetes.py`
Bugfix
N/A
N/A
> fix invalid datetime

- app/apis/api_kubernetes.py
- app/apis/api_service.py
- frontend/configs/config.json
Add sandbox env
- Add sandbox env
Feature
N/A
N/A
> Add sandbox env

- .gitignore
- app/__init__.py
- app/apis/__init__.py
- app/apis/api_application.py
- app/apis/api_kubernetes.py
- app/apis/api_misc.py
- app/apis/api_model.py
- app/apis/common.py
- app/app.py
- app/auth/__init__.py
- app/auth/ldap.py
- app/models/__init__.py
- app/models/kubernetes.py
- app/models/service.py
- app/utils/env_loader.py
- frontend/src/apis/index.tsx
Refactor `dashboard` to be an appropriate architecture.
- Reduce an unnecessary `sys.path.append`
- Create `api_misc,py`
- Change DB schema
Refactor
N/A
N/A
> Refactor flask app

- .gitignore
- app/manage.py
- app/requirements.txt
- app/start.sh
We will plan to change DB schema.
For this, we need to add a DB migration functionality.
- Add requirements of `Flask-Migrate`
- Add migration runner (`manage.py`)
Feature
N/A
```
$ sh ./app/start.sh
```
> Add DB migration

- frontend/src/components/App/Service/ServiceDeployment/index.tsx
In #11 PR, I changed key name. But I forgot to change it in #10 .
- Modify key name
Hotfix
N/A
Execute "Add Service"
> [Hotfix] Modify key name

- frontend/src/apis/Core/index.tsx
When the backend API returned 4xx or 5xx error, it was not handled correctly, so I fixed it
- Do not `throw` in `then`
- Deleted `entryPoint` from arguments since it is unnecessary
Bugfix
N/A
> [Hotfix] Fix error handling for frontend

- app/app.py
Fix inaccurate boolean check
- Fix boolean checker
Bugfix
N/A
N/A
> [Hotfix] Fix inaccurate boolean check

- frontend/README.md
Fix an inaccurate boot command in README.
- Fix an inaccurate boot command
Bugfix
N/A
`API_HOST=http://0.0.0.0 API_PORT=18080 yarn run start`
> [Hotfix] Update README

- README.md
- docker-compose/aws/docker-compose.develop.yaml
- docker-compose/aws/docker-compose.production.yaml
- docker-compose/docker-compose.develop.yaml
- docker-compose/docker-compose.production.yaml
- requirements.txt
fix command in README and docker-compose yml
- fix command in README
- docker-compose yml
- add `urllib3==1.24.1` to prevent version conflict
Bugfix
N/A
`docker-compose -f docker-compose/docker-compose.develop.yaml up`
> fix console command

- frontend/package.json
- frontend/src/app.tsx
- frontend/yarn.lock
remove redux-thunk because it is not used
fix
N/A
`yarn install && yarn start`
> remove redux-thunk

- frontend/src/components/App/Applications/index.tsx
- frontend/src/components/App/Dashboard/index.tsx
- frontend/src/components/App/Services/index.tsx
Disable `Sync` button since this dashboard is already HA configurable.
- Disable button
Feature
N/A
N/A
> Disable `Sync` button

- rekcurd_dashboard/apis/__init__.py
- rekcurd_dashboard/apis/api_kubernetes.py
- rekcurd_dashboard/apis/kubernetes_handler.py
- test/apis/test_api_kubernetes.py
1. Sync from the new Kubernetes cluster if no Kubernetes cluster is registered
2. Sync to the new Kubernetes cluster if at least 1 Kubernetes cluster is registered
- Implement
- unittest
Feature
N/A
unittest
> Sync kubernetes when registered

- rekcurd_dashboard/data_servers/local_handler.py
LocalHanlder does nothing
- does nothing in `delete_file` method
- add comment about role of LocalHandler
Bugfix
N/A
`python -m unittest test/data_servers/*.py`
> LocalHanlder does nothing

- setup.py
Need specifying `long_description_content_type`
- Add `long_description_content_type`
Minor
N/A
N/A
> Specify `long_description_content_type`

- rekcurd_dashboard/apis/api_evaluation.py
Current architecture cannot handle simultaneous access. 
- Use `temfile`
Patch
N/A
```
python -m unittest test/apis/test_api_evaluation.py
```
> Use `tempfile` to avoid the conflict.

- e2e_test/apis/test_service.py
- e2e_test/base.py
- e2e_test/deploy/kube-development-deployment.yml
- test-requirements.txt
> Specify version
