rekcurd/dashboard

- app/apis/api_kubernetes.py
After this modification, you can do a rolling-update when you push `rolling-update` button even if you don't change any configurations.
- Fill `commit_message` automatically
Feature
N/A
Push `rolling-update` button without changing the configurations.
> Add `commit_message` to be a rolling-update trigger

- app/apis/api_kubernetes.py
- app/apis/common.py
To add a convert function and fix the wrong cpu values in `ApiKubernetesIdApplicationIdServiceId`
- A convert function to convert the CPU value from Kubernetes to float
- Apply the convert function
Bugfix
In Drucker, the CPU value should be represented in float but the CPU values from Kubernetes are in string types. This PR try to fix the wrong CPU values in `ApiKubernetesIdApplicationIdServiceId.get`.
With this PR, `ApiKubernetesIdApplicationIdServiceId.get` will return the response sucessfully.
> Add convert function and fix wrong cpu values

- app/apis/api_kubernetes.py
Add `progress_deadline_seconds` option. 
- Avoid infinite retrying of deployment
- (In the future) automatically rollback when deployment fails after `progress_deadline_seconds`.
- Add `progress_deadline_seconds`
Feature
N/A
N/A
> Add `progress_deadline_seconds` option

- frontend/src/apis/Core/index.tsx
Add `JWT_TOKEN_KEY` when fetch `rawMultiRequest`
- Add `JWT_TOKEN_KEY` 
Bugfix
N/A
`Switch model`
`Delete service`
> [Hotfix] Add `JWT_TOKEN_KEY` when fetch `rawMultiRequest`

- frontend/src/apis/Core/index.tsx
When ldap auth is active, `dashboard` never wake.
This is because #11 modified to throw errors correctly ([ref](https://github.com/drucker/drucker-dashboard/pull/11/files#diff-f3d2223f2f8c847aeb6b795ac5660bb5L249)). 
This PR is hotfix that when `/credential` request happens, it escapes throwing error.
- Avoid throwing when credential request comes
Hotfix
N/A
Run with LDAP mode.
> [Hotfix] Avoid throwing when credential request comes

- app/auth/__init__.py
Due to the change in #17, all API requests become error when authentication is enabled.
This is a hotfix for it.
- Fix the path what `@auth_required` decorator ignores authentication processing
Bugfix
N/A
Activated the `auth` part of `settings.yml`
> [Hotfix] Allow `/api/settings` in auth module

- app/auth/__init__.py
In #26 , we specified non `/api/settings` endpoint to be authenticated.
But because of this modification, we cannot use swagger ui now.
- Add constraint `request.path.startswith('/api/')` and `not request.path.startswith('/api/settings')`
Hotfix
N/A
Access to backend swagger UI
`http://localhost:18080/` in default.
> [Hotfix] Specify non-auth endpoint

- app/apis/api_kubernetes.py
- docker-compose/docker-compose.develop.yaml
- docker-compose/docker-compose.production.yaml
To dump a Kubernetes service configuration file, we have to specify an encoding info for Japanese characters.
- Add encoding info when write file.
Bugfix
N/A
Save Japanese character in `memo`
> [Hotfix] Add encode info

- app/app.py
- app/utils/protobuf_util.py
Modify the file upload limit for gRPC and flask.
Since default gRPC settings limits 4MB data for transference in an one connection, we need to fix our file transference setting.
- Specify file upload limit for flask
- Specify file transference limit for gRPC
Bugfix
N/A
Upload ML model more than 4MB.
> [Hotfix] Fix file upload limit for gRPC and flask

- app/apis/api_kubernetes.py
- frontend/src/components/Common/Field/Validateors.tsx
- frontend/src/components/misc/Forms/DeploymentSettingFormFields/index.tsx
Since Kubernetes metadata.name limits up to 63 characters, we need to restrict the length of application name.
- Add restriction of `20` characters for application name.
Bugfix
N/A
Input application name as more than 25 characters.
> [Hotfix] Limit application name length

- app/apis/api_kubernetes.py
- frontend/src/apis/index.tsx
Switching model is always shown as failure on WebUI but actually success.
This is because our API response handler didn't catch the status correctly.
- Fix SwitchModel API response handler
Bugfix
N/A
Switch model on WebUI.
> [Hotfix] Fix `switchModel` API response handler

- app/apis/api_kubernetes.py
Set "DRUCKER_TEST_MODE=False" when it deploys to Kubernetes.
If "DRUCKER_TEST_MODE=True", Drucker uses test database but it's not appropriate for deployment.
- Add "DRUCKER_TEST_MODE" env and set it to "False"
Bugfix
N/A
Create Drucker app and create "settings.yml" which sets "test: True".
> [Hotfix] Set "DRUCKER_TEST_MODE=False" when it deploys to Kubernetes

- app/apis/api_kubernetes.py
- app/app.py
- app/auth/__init__.py
Dumping Kubernetes Service info is too slow. We need to separate it from `update_dbs_kubernetes` method.
- Batch execution for dumping is out of scope on this PR.
- Exception rule of `app/auth/__init__.py` is a temporary. We will use `access_token` of the future expansion.
- Create an endpoint for dump
Minor
#33 
`Sync` on WebUI
> Make dump method independent from update method

- app/README.md
- app/apis/api_application.py
- app/apis/api_service.py
- app/core/drucker_dashboard_client.py
- app/models/__init__.py
- app/models/evaluation.py
- app/models/evaluation_result.py
- app/test/base.py
- app/test/test_api_application.py
- app/test/test_api_service.py
- app/utils/hash_util.py
Not to upload the same evaluation data, separate evaluate and upload test data
- update grpc commit to https://github.com/rekcurd/drucker-grpc-proto/pull/12 
- Add API for UploadEvaluationData (POST and DELETE)
- change models (`Evaluation` -> info for evaluation data,  `EvaluationResult` -> info for evalution result)
- fix Evaluate API based on grpc change.
Feature
N/A
python -m unittest test/test_api_application.py
> separate evaluate and upload test data

- drucker_dashboard/apis/api_admin.py
- drucker_dashboard/auth/__init__.py
We cannot recognize ML applications once we set role to someone to a certain application.
Viewer right should be assigned to everyone. So I set default role to `Role.viewer`.
- Set default role to `Role.viewer`
Bugfix
N/A
```
python -m unittest drucker_dashboard/test/test_access_control.py
```
> Set default role to `Role.viewer`

- drucker_dashboard/apis/api_evaluation.py
- drucker_dashboard/apis/api_kubernetes.py
- drucker_dashboard/models/application_user_role.py
- drucker_dashboard/models/evaluation.py
- drucker_dashboard/models/evaluation_result.py
- drucker_dashboard/utils/__init__.py
- test/test_access_control.py
Because of the `ForeignKey`, we cannot delete `Application` model when we use an authentication.
- Add `backref` to delete orphan
- Change the way of deletion since `query().delete()` doesn't support cascade deletion (See [link](https://docs.sqlalchemy.org/en/latest/orm/query.html#sqlalchemy.orm.query.Query.delete))
Bugfix
N/A
```
python -m unittest drucker_dashboard/test/test_access_control.py
```
> Add cascade deletion for application_user_roles

- drucker_dashboard/apis/api_kubernetes.py
- drucker_dashboard/apis/api_service.py
- e2e_test/base.py
- e2e_test/test_application.py
- e2e_test/test_kubernetes.py
- e2e_test/test_service.py
Cannot work kube.datadir if we change the value after registering kubernetes service. This is because DB entry of kubernetes.config_file is registered using kube.datadir value at the time.
***Important***
After merging this PR, we need to update DB entry by hand.
- Change registration procedure.
- Change loading procedure.
- Fix tests
Bugfix
https://github.com/rekcurd/drucker-dashboard/issues/67
```
python -m unittest
```
> [Bug fix] Fix kube config filepath

- rekcurd_dashboard/apis/api_evaluation.py
- rekcurd_dashboard/rekcurd_dashboard_client.py
- test/test_api_evaluation.py
added label to `EvaluationMetrics` to identify which precision, recall and fvalue correspond to which labels.
`label` is IO type so I used `__get_value_from_io` to get value
Feature
N/A
`python -m unittest test.test_api_evaluation`
> add label to EvaluateResult result

- rekcurd_dashboard/apis/api_evaluation.py
- test/test_api_evaluation.py
I found if multiple services have the same model_id and application_id when evaluating the model,
`Multiple rows were found for one_or_none()` error occurs.
So I change it to `first` 
- allow multiple evaluated services
- fix test
Bugfix
N/A
`python -m unittest test/test_api_evaluation.py`
> Bugfix: allow multiple evaluated services

- rekcurd_dashboard/console_scripts/__init__.py
If db_handler does not have `logger` option,  
[args["logger"] here](https://github.com/rekcurd/dashboard/blob/master/rekcurd_dashboard/console_scripts/db_handler.py#L20) causes `KeyError: 'logger'`, so I added it.
- add logger option to db handler
Bugfix
N/A
`rekcurd_dashboard db init --settings rekcurd_dashboard/template/settings.yml-tpl`
> [Bugfix]add logger option to db handler for KeyError

- rekcurd_dashboard/apis/api_evaluation.py
- rekcurd_dashboard/data_servers/__init__.py
- test/apis/test_api_evaluation.py
dashboard saves evaluation result to db (result column of evaluation_result table),
so not need to save as file
- use evaluation_result from db, not gRPC response
- remove file suffix (because only 1 file is saved in evaluation)
fix
https://github.com/rekcurd/rekcurd-python/issues/45
python -m unittest test/**/*.py
> quit saving evaluate result as file

- rekcurd_dashboard/apis/api_evaluation.py
- rekcurd_dashboard/data_servers/__init__.py
- rekcurd_dashboard/data_servers/aws_s3_handler.py
- rekcurd_dashboard/data_servers/ceph_handler.py
- rekcurd_dashboard/data_servers/data_handler.py
- rekcurd_dashboard/data_servers/local_handler.py
- test/apis/test_api_evaluation.py
- test/data_servers/__init__.py
- test/data_servers/test_data_server.py
update how to deal with evaluation data
- upload evaluations data using DataServer
- delete evaluation data file when EvaluationModel is deleted
- delete evaluation result data file when EvaluationResultModel is deleted
Feature
fixed https://github.com/rekcurd/rekcurd-python/issues/29
python -m unittest test/**/*.py
> delete evaluate files

- rekcurd_dashboard/apis/api_kubernetes_secret.py
- test/apis/test_api_kubernetes_secret.py
show error message when adding git secret with no k8s is registered
Feature
python -m unittest test/apis/test_api_kubernetes_secret.py
> raise exception when adding git secret without k8s

- frontend/src/apis/index.tsx
- frontend/src/components/App/DataServer/DataServerForm.tsx
- frontend/src/components/Common/Enum/index.tsx
- rekcurd_dashboard/apis/api_data_server.py
- rekcurd_dashboard/apis/kubernetes_handler.py
- rekcurd_dashboard/data_servers/__init__.py
- rekcurd_dashboard/data_servers/gcs_handler.py
- rekcurd_dashboard/models/data_server.py
- requirements.txt
- test/apis/test_api_data_server.py
- test/data_servers/__init__.py
- test/data_servers/test_gcs_handler.py
Add GCS support
- Add GcsHandler
- Add UI for `gcs` mode
- Add test
Feature
https://github.com/rekcurd/dashboard/issues/69
Run unittest
> Add GCS support

- README.md
- rekcurd_dashboard/console_scripts/__init__.py
- rekcurd_dashboard/console_scripts/errors.py
- rekcurd_dashboard/console_scripts/template_handler.py
Add `settings.yml` template generation script
- Add CLI option to generate `settings.yml`
Feature
N/A
N/A
> Add `settings.yml` template generation script

- rekcurd_dashboard/apis/api_evaluation.py
- requirements.txt
- tox.ini
remove `duplicated_ok` because I forgot doing so in #103 
- item
- item
- item
fix
N/A
python -m unittest test/apis/test_api_evaluation.py
> remove duplicated_ok
